######################################################################
# Automatically generated by qmake (2.01a) Mo 17. Feb 13:11:24 2014
######################################################################
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = dmsnavigation
DEPENDPATH += . src
INCLUDEPATH += .

# Input
HEADERS += src/DMSNavigation.h
SOURCES += src/DMSNavigation.cpp src/main.cpp
